#! /bin/sh

# set -x

usage() {
  printf "usage:\n  %s [-fb] <input-file>\n\n  -f    financial feed\n  -b    benefit feed\n" $(basename "$0")
}

benefitplans() {
  jq '[ .[]."Benefit Plans".[] | { name: ."Benefit Plan Name", id: ."Benefit Plan ID" } ] | unique' "$1"
}

genders() {
  jq '[ .[]."Members Gender" ] | unique' "$1"
}

maritals() {
  jq '[ .[]."Members Marital Status" ] | unique' "$1"
}

coverages() {
  jq '[ .[]."Benefit Plans".[]."Coverage Name" ] | unique' "$1"
}

relationships() {
  jq '[ .[]."Relationship Code" ] | unique' "$1"
}

deductions() {
  jq '[ .[]."Deductions" | keys ] | flatten | unique' "$1"
}

financial() {
  deductions=$(deductions "$1")
  genders=$(genders "$1")
  maritals=$(maritals "$1")

  printf "Deductions:\n%s\nGenders:\n%s\nMarital Status:\n%s\n" "$deductions" "$genders" "$maritals"
}

benefit() {
  benefitplans=$(benefitplans "$1")
  genders=$(genders "$1")
  maritals=$(maritals "$1")
  coverages=$(coverages "$1")
  relationships=$(relationships "$1")


  printf "Benefit Plans:\n%s\nGenders:\n%s\nMarital Status:\n%s\nCoverage Names:\n%s\nRelationship Codes:\n%s\n" "$benefitplans" "$genders" "$maritals" "$coverages" "$relationships"
}

main() {
  financial=0
  benefit=0
  args=$(getopt 'f:b:' $*); set -- $args

  if [ $# -lt 3 ]; then
    usage
    exit 1
  fi

  while :;
  do
    case $1 in
      -f)
        financial=1
        input=$2
        shift
        ;;
      -b)
        benefit=1
        input=$2
        shift
        ;;
      --)
        shift
        break
        ;;
    esac
    shift
  done

  if [ ! -f "$input" ]; then
    printf "'$input' does not exist.\n"
    exit
  fi

  if [ $benefit -eq 1 ]; then
    benefit "$input"
    exit 0
  elif [ $financial -eq 1 ]; then
    financial "$input"
    exit 0
  else
    usage
    exit 1
  fi

}

main "$@"
